name: Replica3
services:
  neo4j3:
    image: neo4j:4.4.24
    container_name: neo4j3
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_AUTH: none
    ulimits:
      nofile:
        soft: 40000
        hard: 40000

    healthcheck:
      test: [ "CMD", "bash", "-c", "cypher-shell -u neo4j -p verysecretpassword 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - Shared_net

  app3:
    build:
      context: ../
      dockerfile: ./Dockerfiles/wrapperdockerfile
    container_name: Replica3
    ports:
      - "3002:3000"
    environment:
      DATABASE_URI: bolt://neo4j3:7687
      NEO4J_USER: "pandey"
      NEO4J_PASSWORD: "verysecretpassword"
      USER: pandey
      DATABASE: NEO4J
      LOG_LEVEL: error
      LEADER_URI: "http://Replica1:3000"
      MY_URI: "http://Replica3:3000"
    depends_on:
      neo4j3:
        condition: service_healthy
    cap_add:
       - NET_ADMIN
    networks:
      - Replica_net_3
      - Shared_net
networks:
  Replica_net_3:
  Shared_net:
    external: true
